import type { PropertyType } from "./types"

export const featuredProperties: PropertyType[] = [
  {
    id: "prop1",
    title: "Modern 3BHK Apartment in City Center",
    description:
      "A beautifully designed 3BHK apartment with modern amenities, located in the heart of the city. The apartment features a spacious living room, a modern kitchen, and a balcony with a stunning view of the city skyline.",
    location: "City Center, Main Street",
    price: 25000,
    type: "Apartment",
    status: "For Rent",
    bedrooms: 3,
    bathrooms: 2,
    area: 1200,
    image: "/placeholder.svg?height=300&width=400",
    features: ["24/7 Security", "Power Backup", "Parking", "Lift", "Garden"],
    amenities: ["Swimming Pool", "Gym", "Community Hall", "Children's Play Area"],
  },
  {
    id: "prop2",
    title: "Spacious 4BHK Villa with Garden",
    description:
      "A luxurious 4BHK villa with a beautiful garden, located in a peaceful neighborhood. The villa features a large living room, a modern kitchen, and a private garden perfect for family gatherings.",
    location: "Green Valley, Suburb Area",
    price: 8500000,
    type: "Villa",
    status: "For Sale",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    image: "/placeholder.svg?height=300&width=400",
    features: ["24/7 Security", "Power Backup", "Parking", "Garden", "Private Terrace"],
    amenities: ["Swimming Pool", "Gym", "Tennis Court", "Clubhouse"],
  },
  {
    id: "prop3",
    title: "Commercial Space for Office",
    description:
      "A prime commercial space perfect for office setup, located in the business district. The space features open floor plans, modern infrastructure, and ample parking space.",
    location: "Business District, Downtown",
    price: 45000,
    type: "Commercial",
    status: "For Rent",
    area: 1800,
    image: "/placeholder.svg?height=300&width=400",
    features: ["24/7 Security", "Power Backup", "Parking", "Lift", "Conference Room"],
    amenities: ["Cafeteria", "Reception Area", "Meeting Rooms"],
  },
  {
    id: "prop4",
    title: "Residential Plot in Developing Area",
    description:
      "A large residential plot in a rapidly developing area, perfect for building your dream home. The plot is located in a gated community with all basic amenities.",
    location: "New Development Zone, Outskirts",
    price: 3500000,
    type: "Land",
    status: "For Sale",
    area: 2400,
    image: "/placeholder.svg?height=300&width=400",
    features: ["Gated Community", "Water Connection", "Electricity", "Road Access"],
    amenities: ["Park", "Security", "Street Lights"],
  },
  {
    id: "prop5",
    title: "2BHK Budget Apartment",
    description:
      "An affordable 2BHK apartment perfect for small families or bachelors. Located near public transport and markets.",
    location: "Residential Colony, East Side",
    price: 15000,
    type: "Apartment",
    status: "For Rent",
    bedrooms: 2,
    bathrooms: 1,
    area: 850,
    image: "/placeholder.svg?height=300&width=400",
    features: ["Security", "Parking", "Water Supply"],
    amenities: ["Park", "Grocery Store Nearby"],
  },
  {
    id: "prop6",
    title: "Luxury Penthouse with Terrace",
    description:
      "A stunning penthouse with a private terrace offering panoramic views of the city. Features high-end finishes and smart home technology.",
    location: "Luxury Tower, Prime Location",
    price: 12000000,
    type: "Apartment",
    status: "For Sale",
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: "/placeholder.svg?height=300&width=400",
    features: ["Private Terrace", "Smart Home", "Premium Finishes", "High Ceiling"],
    amenities: ["Infinity Pool", "Spa", "Concierge Service", "Private Elevator"],
  },
]

export const allProperties: PropertyType[] = [
  ...featuredProperties,
  {
    id: "prop7",
    title: "Office Space in IT Park",
    description: "A modern office space in a premium IT park with all facilities required for a tech company.",
    location: "Tech Park, IT District",
    price: 60000,
    type: "Commercial",
    status: "For Rent",
    area: 3000,
    image: "/placeholder.svg?height=300&width=400",
    features: ["24/7 Access", "High-speed Internet", "Conference Rooms", "Parking"],
    amenities: ["Cafeteria", "Game Room", "Lounge Area"],
  },
  {
    id: "prop8",
    title: "Farm House with Orchard",
    description: "A beautiful farm house with a fruit orchard, perfect for weekend getaways or retirement.",
    location: "Countryside, 20km from City",
    price: 7500000,
    type: "House",
    status: "For Sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 5000,
    image: "/placeholder.svg?height=300&width=400",
    features: ["Orchard", "Well", "Outhouse", "Storage Barn"],
    amenities: ["Natural Spring", "Hiking Trails Nearby"],
  },
]

